import HomePage from "../components/HomePage";
import { GlobalStyle } from "../components/styles/Body";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Lisas Portfolio</title>
        <meta name="description" content="Generated by moi :)" />
      </Head>
      <HomePage />
    </>
  );
}
